name: ratel-oidc-test

on:
  workflow_dispatch:

permissions:
  id-token: write   # required: lets GitHub mint the OIDC token
  contents: read

jobs:
  read-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Install ratel
        run: npm i -g @ratelkey/cli

      - name: Use OIDC
        run: ratel auth use oidc --burrow "$BURROW_URL" --fingerprint "$BURROW_FINGERPRINT"
        env:
          BURROW_URL: https://54.37.232.208:12010
          BURROW_FINGERPRINT: 13:90:46:78:28:43:46:89:1e:df:a3:12:1b:34:27:c7:8f:83:c4:52:51:5a:7a:b8:00:80:89:65:51:d2:e6:b5

      - name: Read a secret
        run: ratel secret get ratel-test-project/dev/TEST_SECRET
